export default {
    SET_TOAST: 'SET_TOAST',
    REMOVE_TOAST: 'REMOVE_TOAST',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_START: 'REGISTER_START',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_START: 'LOGIN_START',
    LOGIN_FAIL: 'LOGIN_FAIL',
    SET_LOADING: 'SET_LOADING',
    REMOVE_LOADING: 'REMOVE_LOADING',
    USER_LOADED: 'USER_LOADED',
    AUTH_ERROR: 'AUTH_ERROR',
};
